run:
	python manage.py runserver

migrate:
	python manage.py makemigrations
	python manage.py migrate

createsuperuser:
	python manage.py createsuperuser

shell:
	python manage.py shell

test:
	pytest

format:
	black .

lint:
	flake8 .

